DRECK_HTML_MINIFIER_OUTPUT_HTML_PATHS += $(patsubst ./%, ./plugins/html-minifier/generated/%, $(DRECK_HTML_MINIFIER_INPUT_HTML_PATHS))

DRECK_GENERATED_PATHS += $(DRECK_HTML_MINIFIER_OUTPUT_HTML_PATHS)
